(()=>{"use strict";
const COMPETENCIES=[
 {key:"desarrolla-negociacion-v1",plan:"desarrolla-neg-plan-v1",name:"Resolución de conflictos y negociación en SST",short:"Negociación SST"},
 {key:"desarrolla-comunicacion-v1",plan:"desarrolla-comm-plan-v1",name:"Comunicación asertiva aplicada a SST",short:"Comunicación asertiva"},
 {key:"desarrolla-liderazgo-v1",plan:"desarrolla-lead-plan-v1",name:"Liderazgo preventivo en SST",short:"Liderazgo preventivo"},
 {key:"desarrolla-influencia-v1",plan:"desarrolla-inf-plan-v1",name:"Influencia estratégica en SST",short:"Influencia estratégica"},
 {key:"desarrolla-pensamiento-v1",plan:"desarrolla-crit-plan-v1",name:"Pensamiento crítico y toma de decisiones en SST",short:"Pensamiento crítico"},
 {key:"desarrolla-emocional-v1",plan:"desarrolla-emo-plan-v1",name:"Gestión emocional y conversaciones difíciles en SST",short:"Gestión emocional"},
 {key:"desarrolla-finanzas-v1",plan:"desarrolla-fin-plan-v1",name:"Finanzas y Valor Preventivo en SST",short:"Finanzas SST"}
];
const style=document.createElement("style");style.textContent='.report-button{display:inline-flex;align-items:center;justify-content:center;gap:.4rem}.report-button.compact{border:1px solid #007b85;background:#fff;color:#006b74;border-radius:10px;padding:.55rem .75rem;font:700 .78rem Outfit,sans-serif;white-space:nowrap;cursor:pointer}.report-button.compact:hover{background:#eaf7f8}@media(max-width:720px){.result-actions .report-button{width:100%}.cp-title{flex-wrap:wrap}.report-button.compact{order:4;width:100%;margin-top:.35rem;min-height:42px}.competency-progress article{overflow:visible}}';document.head.appendChild(style);
const C={navy:[0,32,91],teal:[0,123,133],green:[112,173,71],amber:[255,182,0],slate:[71,85,105],light:[241,245,249],white:[255,255,255]},roots=["result","commResult","leadResult","influenceResult","criticalResult","emotionResult","financeResult"];
function read(key){try{return JSON.parse(localStorage.getItem(key)||"null")}catch{return null}}
function level(n){return n<45?"Inicial":n<65?"En desarrollo":n<82?"Competente":"Estratégico"}
function person(){try{return JSON.parse(sessionStorage.getItem("desarrolla-session")||"null")?.name||"Participante"}catch{return"Participante"}}
function filename(s){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]+/g,"-").replace(/^-|-$/g,"").toLowerCase()}
function reading(n){if(n<45)return"Requiere acompañamiento y práctica guiada antes de afrontar situaciones de alta exigencia de manera autónoma.";if(n<65)return"Presenta bases útiles, aunque su aplicación puede variar bajo presión o ante interlocutores complejos.";if(n<82)return"Demuestra una actuación consistente en situaciones habituales y puede fortalecer su respuesta en escenarios complejos.";if(n<92)return"Integra la competencia con solidez, anticipa dificultades y sostiene decisiones en contextos exigentes.";return"Demuestra un dominio sobresaliente y puede modelar, facilitar y acompañar el desarrollo de otras personas."}
function advice(d,n){d=d.toLowerCase();if(n<45)return`Practicar ${d} mediante una situación breve y guiada; pedir retroalimentación basada en conductas observables.`;if(n<65)return`Aplicar una herramienta concreta de ${d} en una situación real y registrar qué funcionó y qué debe ajustarse.`;if(n<82)return`Llevar ${d} a un caso de mayor complejidad, comparar alternativas y verificar el efecto de la decisión.`;return`Conservar la fortaleza en ${d}, compartir la práctica con otras personas y reunir evidencia de su impacto.`}
function sorted(r){return Object.entries(r.scores||{}).sort((a,b)=>b[1]-a[1])}
function header(doc,title,page){doc.setFillColor(...C.navy);doc.rect(0,0,210,27,"F");doc.setTextColor(...C.white);doc.setFont("helvetica","bold");doc.setFontSize(12);doc.text("LA MOVIDA DE SST+",15,11);doc.setFontSize(8);doc.setFont("helvetica","normal");doc.text("De la Reacción a la Prevención",15,17);doc.text(`INFORME PERSONAL · ${page}/2`,195,14,{align:"right"});doc.setTextColor(...C.navy);doc.setFont("helvetica","bold");doc.setFontSize(15);doc.text(title,15,38,{maxWidth:180})}
function footer(doc){doc.setDrawColor(210,220,230);doc.line(15,284,195,284);doc.setTextColor(...C.slate);doc.setFontSize(7);doc.setFont("helvetica","normal");doc.text("Academia Movida de SST · www.movidasst.com",15,290);doc.text("Autodiagnóstico formativo: no es certificación profesional ni evaluación psicológica.",195,290,{align:"right"})}
function wrap(doc,text,x,y,width,size=9,style="normal",color=C.slate){doc.setFont("helvetica",style);doc.setFontSize(size);doc.setTextColor(...color);const lines=doc.splitTextToSize(String(text||""),width);doc.text(lines,x,y);return y+lines.length*(size*.42)+2}
function section(doc,title,y){doc.setFillColor(...C.light);doc.roundedRect(15,y,180,9,2,2,"F");doc.setTextColor(...C.navy);doc.setFont("helvetica","bold");doc.setFontSize(9);doc.text(title.toUpperCase(),19,y+6);return y+15}
function bar(doc,label,score,y){doc.setTextColor(...C.navy);doc.setFont("helvetica","bold");doc.setFontSize(8);doc.text(label,15,y,{maxWidth:135});doc.text(`${score}%`,195,y,{align:"right"});doc.setFillColor(226,232,240);doc.roundedRect(15,y+3,180,4,2,2,"F");doc.setFillColor(...(score<45?C.amber:score<65?C.teal:C.green));doc.roundedRect(15,y+3,Math.max(3,180*score/100),4,2,2,"F");return y+14}
function fallback(c,r,p){const w=window.open("","_blank");if(!w)return alert("Permite las ventanas emergentes para generar el informe.");const list=sorted(r),rows=list.map(([d,n])=>`<tr><td>${d}</td><td>${n}%</td></tr>`).join("");w.document.write(`<!doctype html><meta charset="utf-8"><title>Informe ${c.short}</title><style>body{font:15px Arial;color:#334155;margin:35px}h1,h2{color:#00205b}.score{font-size:52px;font-weight:bold;color:#007b85}table{width:100%;border-collapse:collapse}td{padding:10px;border-bottom:1px solid #ddd}@media print{button{display:none}}</style><h1>Informe personal de autodiagnóstico</h1><h2>${c.name}</h2><p>${person()} · ${new Date(r.date).toLocaleDateString("es")}</p><div class="score">${r.overall}%</div><h2>Nivel ${level(r.overall)}</h2><p>${reading(r.overall)}</p><table>${rows}</table><h2>Plan de mejora</h2><p><b>Prioridad:</b> ${p?.dimension||list.at(-1)[0]}</p><p>${p?.action||advice(...list.at(-1))}</p><p><small>Autodiagnóstico formativo. No constituye certificación profesional ni evaluación psicológica.</small></p><button onclick="print()">Guardar como PDF</button>`);w.document.close()}
function generate(c){const r=read(c.key);if(!r?.scores)return alert("Primero completa el autodiagnóstico de esta competencia.");const p=read(c.plan),api=window.jspdf;if(!api?.jsPDF)return fallback(c,r,p);const doc=new api.jsPDF({unit:"mm",format:"a4",compress:true}),list=sorted(r),priority=list.at(-1),date=new Date(r.date||Date.now()).toLocaleDateString("es-CL",{day:"2-digit",month:"long",year:"numeric"});
 header(doc,"Informe personal de autodiagnóstico",1);let y=50;doc.setTextColor(...C.teal);doc.setFont("helvetica","bold");doc.setFontSize(12);doc.text(c.name,15,y,{maxWidth:180});y+=13;doc.setFillColor(...C.light);doc.roundedRect(15,y,180,39,3,3,"F");doc.setTextColor(...C.navy);doc.setFontSize(8);doc.text("PARTICIPANTE",21,y+8);doc.setFontSize(12);doc.text(person(),21,y+16,{maxWidth:105});doc.setFontSize(8);doc.text(`Fecha: ${date}`,21,y+27);doc.setTextColor(...C.teal);doc.setFontSize(30);doc.text(`${r.overall}%`,184,y+18,{align:"right"});doc.setTextColor(...C.navy);doc.setFontSize(10);doc.text(`Nivel ${level(r.overall)}`,184,y+29,{align:"right"});y+=48;y=section(doc,"Lectura del resultado",y);y=wrap(doc,reading(r.overall),15,y,180,9)+2;y=section(doc,"Resultados por dimensión",y);list.forEach(x=>y=bar(doc,x[0],x[1],y));footer(doc);
 doc.addPage();header(doc,"Interpretación y ruta de mejora",2);y=50;y=section(doc,"Fortalezas para sostener",y);list.slice(0,2).forEach(([d,n])=>{y=wrap(doc,`${d} (${n}%): ${advice(d,n)}`,18,y,174,9)+2});y+=2;y=section(doc,"Prioridades de desarrollo",y);list.slice(-2).reverse().forEach(([d,n])=>{y=wrap(doc,`${d} (${n}%): ${advice(d,n)}`,18,y,174,9)+2});y+=2;y=section(doc,"Plan de acción de 30 días",y);const actions=p?[`Situación de aplicación: ${p.situation||"Por definir"}`,`Conducta comprometida: ${p.action||"Por definir"}`,`Evidencia esperada: ${p.evidence||"Por definir"}`,`Fecha de revisión: ${p.date||"Por definir"}`]:[`Semana 1 · Observa y registra una situación relacionada con ${priority[0].toLowerCase()}.`,`Semana 2 · Estudia y practica una herramienta aplicable a esa situación.`,`Semana 3 · Aplica la conducta en un caso real y solicita retroalimentación.`,`Semana 4 · Revisa la evidencia, documenta el aprendizaje y ajusta la acción.`];actions.forEach((a,i)=>{doc.setFillColor(...(i===0?C.teal:C.light));doc.circle(20,y-1,3,"F");y=wrap(doc,a,27,y,164,9,i===0?"bold":"normal",C.slate)+3});y+=1;y=section(doc,"Cómo utilizar este informe",y);y=wrap(doc,"Úsalo como línea base para conversar con una persona mentora, seleccionar situaciones de práctica y comparar tu evolución al repetir el autodiagnóstico. La puntuación expresa la frecuencia declarada de conductas y debe complementarse con evidencia y retroalimentación.",15,y,180,9)+5;doc.setFillColor(255,248,224);doc.roundedRect(15,y,180,22,3,3,"F");wrap(doc,"Este informe es independiente del certificado. El informe orienta el desarrollo; la insignia reconoce la ruta completa; los 100 XP reconocen la culminación; el certificado se habilita después de validar el pago.",20,y+7,170,8,"bold",C.navy);footer(doc);doc.save(`informe-${filename(c.short)}-${filename(person())}.pdf`)}
function button(c,compact=false){const b=document.createElement("button");b.type="button";b.className=compact?"report-button compact":"secondary report-button";b.textContent=compact?"↓ Informe PDF":"↓ Descargar informe PDF";b.onclick=()=>generate(c);return b}
function mountResults(){roots.forEach((id,i)=>{const actions=document.getElementById(id)?.querySelector(".result-actions");if(actions&&!actions.querySelector(".report-button"))actions.appendChild(button(COMPETENCIES[i]))})}
function mountProgress(){document.querySelectorAll("#globalProgress .competency-progress article").forEach((card,i)=>{if(read(COMPETENCIES[i].key)&&!card.querySelector(".report-button"))card.querySelector(".cp-title")?.appendChild(button(COMPETENCIES[i],true))})}
new MutationObserver(()=>{mountResults();mountProgress()}).observe(document.body,{childList:true,subtree:true});mountResults();mountProgress();window.DesarrollaInformes={generate:key=>{const c=COMPETENCIES.find(x=>x.key===key);if(c)generate(c)}};
})();
