(()=>{"use strict";
const U="https://lfdmbkzghnwvsapxypvt.supabase.co",K="sb_publishable_bRnkA6PA8-v073nrw9zxiQ_8rVGiOn1",API=U+"/functions/v1/desarrolla-roleplay-calibration",$=id=>document.getElementById(id),client=supabase.createClient(U,K);
const bank=window.DesarrollaCalibrationBank;let running=false,controller=null,lastRun=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pct=(n,d)=>d?Math.round(n*1000/d)/10:0;
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const median=a=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
const date=v=>v?new Intl.DateTimeFormat("es-CL",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
function selectedTests(){let t=bank.tests.slice(),scope=$("calScope").value,comp=$("calCompetency").value,level=$("calLevel").value;if(scope==="smoke")t=t.filter(x=>/1-/.test(x.id));if(comp)t=t.filter(x=>x.competency===comp);if(level)t=t.filter(x=>x.level===level);return t}
function updateCount(){const n=selectedTests().length,r=+$("calRepeats").value||1;$("calRun").textContent=`Ejecutar ${n} prueba${n===1?"":"s"}${r>1?` × ${r}`:""}`}
function setProgress(done,total,text){const p=total?Math.round(done/total*100):0;$("calProgress").hidden=false;$("calProgressText").textContent=text||`${done} de ${total}`;$("calProgressPct").textContent=p+"%";$("calProgressBar").style.width=p+"%"}
async function adminSession(){const {data:{session}}=await client.auth.getSession();if(!session)throw Error("Sesión administrativa requerida.");const {data:isAdmin,error}=await client.rpc("is_app_admin");if(error||isAdmin!==true)throw Error("La cuenta no tiene permiso administrativo.");return session}
async function batchCall(session,items){const r=await fetch(API,{method:"POST",signal:controller?.signal,headers:{"Content-Type":"application/json","Authorization":`Bearer ${session.access_token}`},body:JSON.stringify({tests:items.map(x=>({id:x.test.id,competency:x.test.competency,answer:x.test.answer,scenario:x.test.scenario}))})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw Error(d?.message||"Falló un lote de calibración.");return d}
function attemptResult(item,res){if(!res?.ok)return{test_id:item.test.id,competency:item.test.competency,level:item.test.level,repeat:item.repeat,error:res?.error||"Error de evaluación",passed:false};const ev=res.evaluation||{},score=Number(ev.total||0),exp=item.test.expected,rangePass=score>=exp.min&&score<=exp.max,critical=Boolean(ev.riesgo_critico),criticalPass=critical===Boolean(exp.critical);return{test_id:item.test.id,competency:item.test.competency,level:item.test.level,repeat:item.repeat,model:res.model,score,critical,expected_critical:exp.critical,range_min:exp.min,range_max:exp.max,range_pass:rangePass,critical_pass:criticalPass,passed:rangePass&&criticalPass,quality:ev.quality,status:ev.conversation?.status||"",dimensions:ev.dimensions||[],fortaleza:ev.fortaleza||"",oportunidad:ev.oportunidad||""}}
function summarize(results){const ok=results.filter(x=>!x.error),total=results.length,passed=results.filter(x=>x.passed).length,rangePass=results.filter(x=>x.range_pass).length,critPass=results.filter(x=>x.critical_pass).length;let tp=0,tn=0,fp=0,fn=0;for(const x of ok){if(x.expected_critical&&x.critical)tp++;else if(x.expected_critical&&!x.critical)fn++;else if(!x.expected_critical&&x.critical)fp++;else tn++}const dev=ok.map(x=>Math.abs(x.score-(x.range_min+x.range_max)/2));const grouped={};for(const x of ok)(grouped[x.test_id]??=[]).push(x);let consistent=0,groups=0;for(const g of Object.values(grouped)){if(g.length<2)continue;groups++;const scores=g.map(x=>x.score),criticalStable=new Set(g.map(x=>x.critical)).size===1;if(Math.max(...scores)-Math.min(...scores)<=12&&criticalStable)consistent++}const byComp={};for(const c of Object.keys(bank.competencies)){const a=results.filter(x=>x.competency===c);if(a.length)byComp[c]={attempts:a.length,passed:a.filter(x=>x.passed).length,pass_rate:pct(a.filter(x=>x.passed).length,a.length),median_score:median(a.filter(x=>!x.error).map(x=>x.score))}}return{total_attempts:total,successful:ok.length,errors:total-ok.length,passed,pass_rate:pct(passed,total),range_pass_rate:pct(rangePass,total),critical_accuracy:pct(critPass,total),critical_recall:pct(tp,tp+fn),critical_precision:pct(tp,tp+fp),false_positives:fp,false_negatives:fn,mean_abs_midpoint_deviation:Math.round(mean(dev)*10)/10,consistency_groups:groups,consistency_pass_rate:groups?pct(consistent,groups):null,by_competency:byComp}}
function aggregate(results){const m={};for(const r of results)(m[r.test_id]??=[]).push(r);return Object.entries(m).map(([id,rows])=>({id,rows,test:bank.tests.find(t=>t.id===id)}))}
function render(summary,results,meta){$("calMetrics").hidden=false;$("calReport").hidden=false;$("calCsv").disabled=false;$("calMetrics").innerHTML=`<article><span>Aprobación global</span><b>${summary.pass_rate}%</b></article><article><span>Rango esperado</span><b>${summary.range_pass_rate}%</b></article><article><span>Detección crítica</span><b>${summary.critical_accuracy}%</b></article><article><span>Recall crítico</span><b>${summary.critical_recall}%</b></article><article><span>Falsos positivos</span><b>${summary.false_positives}</b></article><article><span>Falsos negativos</span><b>${summary.false_negatives}</b></article><article><span>Desviación media</span><b>${summary.mean_abs_midpoint_deviation} pts</b></article><article><span>Consistencia</span><b>${summary.consistency_pass_rate==null?"—":summary.consistency_pass_rate+"%"}</b></article>`;$("calReportMeta").textContent=`${meta.tests} casos · ${meta.repetitions} repetición${meta.repetitions===1?"":"es"} · ${meta.model||"modelo no reportado"} · banco ${bank.version}`;
 const compCards=Object.entries(summary.by_competency).map(([k,v])=>`<article><b>${esc(bank.competencies[k])}</b><p>${v.pass_rate}% dentro de criterio · mediana ${v.median_score}% · ${v.passed}/${v.attempts} intentos aprobados</p></article>`).join("");
 $("calDiagnostics").innerHTML=compCards+`<article><b>Riesgo crítico</b><p>Precisión ${summary.critical_precision}% · recall ${summary.critical_recall}% · FP ${summary.false_positives} · FN ${summary.false_negatives}</p></article><article><b>Lectura</b><p>Una falla no significa automáticamente que Gemini esté mal: identifica qué patrón necesita ajuste de rúbrica, prompt o rango esperado.</p></article>`;
 const groups=aggregate(results);$("calRows").innerHTML=groups.map(g=>{const scores=g.rows.filter(x=>!x.error).map(x=>x.score),passes=g.rows.filter(x=>x.passed).length,crit=g.rows.filter(x=>!x.error).map(x=>x.critical),ok=passes===g.rows.length&&!g.rows.some(x=>x.error);return`<tr><td><b>${esc(g.id)}</b><small>${esc(g.test.scenario.caseName)}</small></td><td>${esc(bank.competencies[g.test.competency])}</td><td>${esc(g.test.level)}</td><td>${g.test.expected.min}–${g.test.expected.max}%<small>Crítico: ${g.test.expected.critical?"sí":"no"}</small></td><td><strong>${scores.length?scores.join(" · ")+"%":"Error"}</strong><small>${scores.length>1?`amplitud ${Math.max(...scores)-Math.min(...scores)} pts`:""}</small></td><td>${crit.length?crit.map(v=>v?"Sí":"No").join(" · "):"—"}</td><td class="${ok?"cal-pass":"cal-fail"}">${ok?"Cumple":`${passes}/${g.rows.length} cumple`}</td></tr>`}).join("")}
function csv(results){const h=["test_id","competency","level","repeat","score","range_min","range_max","critical","expected_critical","range_pass","critical_pass","passed","model","error"],q=v=>`"${String(v??"").replace(/"/g,'""')}"`,rows=[h.join(",")].concat(results.map(x=>h.map(k=>q(x[k])).join(",")));const blob=new Blob([rows.join("\n")],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`calibracion-desarrolla-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function saveRun(summary,results,meta,status){const compact=results.map(x=>({test_id:x.test_id,competency:x.competency,level:x.level,repeat:x.repeat,score:x.score??null,critical:x.critical??null,passed:x.passed,error:x.error||null,model:x.model||null,status:x.status||null,dimensions:x.dimensions||[]}));const {data,error}=await client.rpc("desarrolla_calibration_guardar",{p_bank_version:bank.version,p_model:meta.model||"",p_repetitions:meta.repetitions,p_summary:summary,p_results:compact,p_status:status});if(error)throw error;return data}
async function history(){const {data,error}=await client.rpc("desarrolla_calibration_historial",{p_limit:12});if(error){$("calHistory").innerHTML='<p>No se pudo cargar el historial.</p>';return}const rows=Array.isArray(data)?data:[];$("calHistory").innerHTML=rows.length?rows.map(x=>`<article><div><h3>${date(x.created_at)} · banco ${esc(x.bank_version)}</h3><p>${x.total_tests} intentos · ${x.repetitions} repetición${x.repetitions===1?"":"es"} · ${esc(x.model||"modelo no registrado")}</p></div><div><strong class="${esc(x.status)}">${x.summary?.pass_rate??0}%</strong><p>${esc(x.status)}</p></div></article>`).join(""):'<p>Aún no hay calibraciones guardadas.</p>'}
async function run(){if(running)return;const tests=selectedTests(),reps=+$("calRepeats").value||1;if(!tests.length){$("calMessage").textContent="No hay pruebas con esos filtros.";return}running=true;controller=new AbortController();$("calRun").disabled=true;$("calCancel").disabled=false;$("calCsv").disabled=true;$("calMessage").textContent="";let results=[],model="",status="completed";try{const session=await adminSession(),queue=[];for(let repeat=1;repeat<=reps;repeat++)for(const test of tests)queue.push({test,repeat});for(let i=0;i<queue.length;i+=4){if(!running){status="partial";break}const items=queue.slice(i,i+4);setProgress(i,queue.length,`Evaluando ${i+1}–${Math.min(i+items.length,queue.length)} de ${queue.length}…`);let d;try{d=await batchCall(session,items)}catch(e){if(e.name==="AbortError"){status="partial";break}d={results:items.map(x=>({ok:false,id:x.test.id,competency:x.test.competency,error:e.message}))}}for(let j=0;j<items.length;j++){const ar=attemptResult(items[j],d.results?.[j]);results.push(ar);if(ar.model&&!model)model=ar.model}}setProgress(results.length,queue.length,`${results.length} de ${queue.length} intentos completados`)}const summary=summarize(results),meta={tests:tests.length,repetitions:reps,model};lastRun={summary,results,meta};render(summary,results,meta);await saveRun(summary,results,meta,status);await history();$("calMessage").textContent=status==="completed"?"Calibración completada y guardada.":"Calibración parcial guardada."}catch(e){console.error(e);$("calMessage").textContent=e.message||"No se pudo ejecutar la calibración."}finally{running=false;controller=null;$("calRun").disabled=false;$("calCancel").disabled=true}}
async function init(){try{const session=await adminSession();$("calAdmin").textContent=session.user.email||"Administrador";$("calLoading").hidden=true;$("calApp").hidden=false;$("bankCount").textContent=bank.tests.length;updateCount();await history()}catch(e){$("calLoading").innerHTML=`<div><b>Acceso restringido</b><span>${esc(e.message)}</span><a href="admin.html">Ir a Administración</a></div>`}}
["calScope","calCompetency","calLevel","calRepeats"].forEach(id=>$(id).onchange=updateCount);$("calRun").onclick=run;$("calCancel").onclick=()=>{running=false;controller?.abort()};$("calCsv").onclick=()=>lastRun&&csv(lastRun.results);$("calRefreshHistory").onclick=history;init();
})();