(()=>{"use strict";
const U="https://lfdmbkzghnwvsapxypvt.supabase.co",K="sb_publishable_bRnkA6PA8-v073nrw9zxiQ_8rVGiOn1",$=id=>document.getElementById(id),client=supabase.createClient(U,K);
const names={negotiation:"Negociación",communication:"Comunicación asertiva",leadership:"Liderazgo preventivo",influence:"Influencia estratégica",critical:"Pensamiento crítico",emotional:"Gestión emocional",finance:"Finanzas y Valor Preventivo"};
let rows=[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const date=v=>v?new Intl.DateTimeFormat("es-CL",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
function guidedTemplate(values=[]){const seed=[0,1,2].map(i=>values[i]||["",i===0?2:i===1?0:-1,""]);$("guidedRows").innerHTML=seed.map((v,i)=>`<div class="guided-row" data-guided="${i}"><input class="g-text" maxlength="500" placeholder="Opción ${i+1}" value="${esc(v[0])}"><select class="g-score"><option value="2" ${Number(v[1])===2?"selected":""}>Sólida +2</option><option value="1" ${Number(v[1])===1?"selected":""}>Buena +1</option><option value="0" ${Number(v[1])===0?"selected":""}>Parcial 0</option><option value="-1" ${Number(v[1])===-1?"selected":""}>Riesgo -1</option></select><textarea class="g-feedback" rows="2" maxlength="600" placeholder="Retroalimentación para esta opción">${esc(v[2])}</textarea></div>`).join("")}
function collectGuided(){return[...document.querySelectorAll("[data-guided]")].map(r=>[r.querySelector(".g-text").value.trim(),Number(r.querySelector(".g-score").value),r.querySelector(".g-feedback").value.trim()]).filter(x=>x[0])}
function reset(){ $("caseForm").reset();$("caseId").value="";$("caseIcon").value="🎭";$("caseDifficulty").value="2";$("caseOrder").value="100";$("caseActive").checked=true;$("caseAiOnly").checked=false;$("formTitle").textContent="Nuevo caso";$("caseDelete").hidden=true;$("caseMessage").textContent="";guidedTemplate([])}
async function adminSession(){const {data:{session}}=await client.auth.getSession();if(!session)throw Error("Sesión administrativa requerida.");const {data:isAdmin,error}=await client.rpc("is_app_admin");if(error||isAdmin!==true)throw Error("La cuenta no tiene permiso administrativo.");return session}
async function load(){const {data,error}=await client.rpc("desarrolla_admin_roleplay_cases");if(error||!data?.ok)throw error||Error("No se pudo cargar la biblioteca.");rows=data.cases||[];render()}
function stats(){const active=rows.filter(x=>x.active).length,custom=rows.filter(x=>x.source==="custom").length,aiOnly=rows.filter(x=>x.ai_only).length;$("caseKpis").innerHTML=`<article><span>Total de casos</span><b>${rows.length}</b></article><article><span>Activos</span><b>${active}</b></article><article><span>Casos base</span><b>${rows.length-custom}</b></article><article><span>Creados por ti</span><b>${custom}</b></article><article><span>Solo IA</span><b>${aiOnly}</b></article><article><span>Competencias</span><b>${new Set(rows.map(x=>x.competency)).size}</b></article>`}
function filtered(){const q=$("caseSearch").value.trim().toLowerCase(),comp=$("caseFilterComp").value,state=$("caseFilterState").value;return rows.filter(x=>(!q||[x.actor_name,x.case_name,x.context,x.opening,x.goal,x.limit_text].some(v=>String(v||"").toLowerCase().includes(q)))&&(!comp||x.competency===comp)&&(!state||(state==="active"&&x.active)||(state==="inactive"&&!x.active)||(state==="builtin"&&x.source==="builtin")||(state==="custom"&&x.source==="custom")))}
function render(){stats();const list=filtered();$("caseCount").textContent=`${list.length} caso${list.length===1?"":"s"}`;$("caseCards").innerHTML=list.length?list.map(x=>`<article class="case-card ${x.active?"":"inactive"}"><div><span class="case-source">${x.source==="builtin"?"Caso base":"Caso creado"} · ${esc(names[x.competency]||x.competency)}</span><h3>${esc(x.icon)} ${esc(x.case_name)}</h3><p><b>${esc(x.actor_name)}</b> · ${esc(x.context)}</p><div class="meta"><span>Dificultad ${x.difficulty}/5</span><span>${x.active?"Activo":"Inactivo"}</span><span>${x.ai_only?"Solo IA":"IA + guiado"}</span><span>Orden ${x.sort_order}</span></div></div><button data-edit="${x.id}">Editar</button></article>`).join(""):'<div class="case-empty">No hay casos con estos filtros.</div>';document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>edit(rows.find(x=>x.id===b.dataset.edit)))}
function edit(x){if(!x)return;$("caseId").value=x.id;$("caseCompetency").value=x.competency;$("caseIcon").value=x.icon||"🎭";$("caseActor").value=x.actor_name||"";$("caseName").value=x.case_name||"";$("caseContext").value=x.context||"";$("caseOpening").value=x.opening||"";$("caseGoal").value=x.goal||"";$("caseLimit").value=x.limit_text||"";$("caseCritical").value=x.critical_rules||"";$("caseDifficulty").value=String(x.difficulty||2);$("caseOrder").value=String(x.sort_order??100);$("caseActive").checked=Boolean(x.active);$("caseAiOnly").checked=Boolean(x.ai_only);guidedTemplate(x.guided_choices||[]);$("formTitle").textContent="Editar caso";$("caseDelete").hidden=false;$("caseMessage").textContent=`${x.source==="builtin"?"Caso base":"Caso creado"} · actualizado ${date(x.updated_at)}`;window.scrollTo({top:0,behavior:"smooth"})}
async function save(e){e.preventDefault();const guided=collectGuided(),payload={id:$("caseId").value||null,competency:$("caseCompetency").value,icon:$("caseIcon").value.trim()||"🎭",actor_name:$("caseActor").value.trim(),case_name:$("caseName").value.trim(),context:$("caseContext").value.trim(),opening:$("caseOpening").value.trim(),goal:$("caseGoal").value.trim(),limit_text:$("caseLimit").value.trim(),critical_rules:$("caseCritical").value.trim(),difficulty:Number($("caseDifficulty").value)||2,sort_order:Number($("caseOrder").value)||0,active:$("caseActive").checked,ai_only:$("caseAiOnly").checked||guided.length===0,guided_choices:guided};$("caseSave").disabled=true;$("caseMessage").textContent="Guardando…";const {data,error}=await client.rpc("desarrolla_admin_roleplay_case_upsert",{p_payload:payload});$("caseSave").disabled=false;if(error||!data?.ok){$("caseMessage").textContent=error?.message||"No se pudo guardar el caso.";return}$("caseMessage").textContent="Caso guardado correctamente.";await load();const saved=rows.find(x=>x.id===data.id);if(saved)edit(saved)}
async function remove(){const id=$("caseId").value,x=rows.find(r=>r.id===id);if(!id||!x)return;if(!confirm(`¿Eliminar definitivamente el caso “${x.case_name}”?\n\nSi solo quieres retirarlo de la práctica, es mejor desactivar “Activo”.`))return;$("caseDelete").disabled=true;const {data,error}=await client.rpc("desarrolla_admin_roleplay_case_delete",{p_id:id});$("caseDelete").disabled=false;if(error||!data?.ok){$("caseMessage").textContent=error?.message||"No se pudo eliminar.";return}reset();await load()}
async function init(){guidedTemplate([]);try{const session=await adminSession();$("casesAdmin").textContent=session.user.email||"Administrador";await load();$("casesLoading").hidden=true;$("casesApp").hidden=false}catch(e){$("casesLoading").innerHTML=`<div><b>Acceso restringido</b><span>${esc(e.message)}</span><a href="admin.html">Ir a Administración</a></div>`}}
$("caseForm").onsubmit=save;$("caseDelete").onclick=remove;$("caseReset").onclick=reset;$("caseSearch").oninput=render;$("caseFilterComp").onchange=render;$("caseFilterState").onchange=render;$("caseAiOnly").onchange=()=>{$("guidedBlock").open=!$("caseAiOnly").checked};init();
})();