(()=>{"use strict";
const $=id=>document.getElementById(id),KEY="desarrolla-finanzas-v1",TOKEN="desarrolla-ranking-token",URL="https://lfdmbkzghnwvsapxypvt.supabase.co",API="sb_publishable_bRnkA6PA8-v073nrw9zxiQ_8rVGiOn1";
const detail={
"Lenguaje financiero":"Comprendes ingresos, costos, gasto, inversión, margen, flujo de caja y métricas financieras sin confundirlas.",
"Presupuesto y partidas":"Planificas partidas, forecast, ejecución y desviaciones del presupuesto de SST.",
"CAPEX y OPEX":"Distingues inversión inicial, gasto operativo y costos recurrentes de una solución preventiva.",
"Costo económico del riesgo":"Reconoces costos directos, indirectos, interrupciones, productividad y costos evitables sin inventar cifras.",
"Evaluación de inversiones":"Interpretas ROI, payback, TCO y, cuando corresponde, VAN/TIR con supuestos explícitos.",
"Escenarios e incertidumbre":"Trabajas con rangos, sensibilidad, escenario conservador/base/favorable y límites de la estimación.",
"Argumentación ejecutiva":"Transformas evidencia técnica en una propuesta económica clara para Finanzas, Operaciones y Dirección.",
"Integridad preventiva":"Usas el análisis económico para comparar alternativas sin monetizar derechos ni justificar exposiciones inaceptables."
};
const questions=[
["Lenguaje financiero","Puedo explicar la diferencia entre costo, gasto e inversión al presentar una necesidad de SST."],
["Lenguaje financiero","Comprendo cómo el margen de la empresa cambia el impacto de una pérdida o ahorro."],
["Lenguaje financiero","Puedo conversar con Finanzas usando conceptos básicos de caja, presupuesto y retorno sin ocultar mis límites técnicos."],
["Presupuesto y partidas","Construyo un presupuesto de SST separando partidas y responsables de ejecución."],
["Presupuesto y partidas","Comparo presupuesto aprobado, gasto real y forecast para explicar desviaciones."],
["Presupuesto y partidas","Puedo justificar por qué una partida debe mantenerse, reprogramarse o priorizarse."],
["CAPEX y OPEX","Diferencio correctamente CAPEX de OPEX al analizar una solución preventiva."],
["CAPEX y OPEX","Incluyo instalación, mantenimiento, consumibles, formación y verificación cuando estimo el costo de una solución."],
["CAPEX y OPEX","Evito comparar alternativas únicamente por el precio de compra inicial."],
["Costo económico del riesgo","Distingo costos directos de costos indirectos asociados a incidentes o exposición."],
["Costo económico del riesgo","Puedo estimar el costo de una interrupción sin presentarlo como certeza cuando depende de supuestos."],
["Costo económico del riesgo","Relaciono pérdidas, productividad y continuidad operacional con evidencia verificable."],
["Evaluación de inversiones","Puedo calcular e interpretar un ROI simple de una intervención de SST."],
["Evaluación de inversiones","Puedo calcular un período de recuperación o payback y explicar sus limitaciones."],
["Evaluación de inversiones","Comprendo cuándo TCO, VAN o TIR aportan información adicional a la decisión."],
["Escenarios e incertidumbre","Separo claramente datos observados, supuestos y estimaciones."],
["Escenarios e incertidumbre","Presento escenarios conservador, base y favorable cuando la incertidumbre económica es relevante."],
["Escenarios e incertidumbre","Puedo identificar qué supuesto tiene mayor efecto sobre la recomendación."],
["Argumentación ejecutiva","Puedo resumir en pocos minutos problema, opciones, inversión, beneficio, riesgo residual y decisión requerida."],
["Argumentación ejecutiva","Adapto el nivel de detalle al hablar con Finanzas, Operaciones o Junta Directiva."],
["Argumentación ejecutiva","Comparo alternativas usando criterios técnicos, económicos y operativos, no solo una cifra de ROI."],
["Integridad preventiva","No manipulo probabilidades, costos o beneficios para conseguir presupuesto."],
["Integridad preventiva","No considero aceptable mantener una exposición inaceptable solo porque una solución tenga ROI negativo."],
["Integridad preventiva","Explico cuándo un costo evitado es hipotético y no un ahorro garantizado."]
];
const labels=["Casi nunca","Pocas veces","Algunas veces","Frecuentemente","Casi siempre"];let current=0,answers=Array(24).fill(null);
function level(n){return n<45?"Inicial":n<65?"En desarrollo":n<82?"Aplicación consistente":"Fortaleza declarada"}function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(id)?.classList.add("active");document.querySelectorAll("nav button").forEach(b=>b.classList.remove("active"));scrollTo({top:0,behavior:"smooth"})}
function build(){const cards=document.querySelectorAll("#skills .card"),card=cards[6];if(card){card.classList.add("available");card.querySelector(".tag").className="tag ready";card.querySelector(".tag").textContent="Disponible";if(!card.querySelector("button")){const btn=document.createElement("button");btn.className="primary full";btn.textContent="Abrir competencia";btn.onclick=()=>show("finance-skill");card.appendChild(btn)}else card.querySelector("button").onclick=()=>show("finance-skill")}
document.querySelector("main").insertAdjacentHTML("beforeend",`<section id="finance-skill" class="view"><button class="back finance-back">← Volver a competencias</button><div class="module"><div><span class="tag ready">Competencia 07</span><h1>Finanzas y Valor Preventivo en SST</h1><p>Aprende a traducir riesgos, controles e inversiones de SST al lenguaje económico de la organización sin perder el criterio preventivo.</p></div><div class="facts"><span><b>24</b>afirmaciones</span><span><b>8</b>dimensiones</span><span><b>12</b>minutos</span></div></div><aside class="notice"><b>No necesitas ser financiero.</b> El objetivo es comprender cómo se toman decisiones económicas y construir propuestas responsables, transparentes y comparables.</aside><div class="dimensions"><h2>¿Qué vas a explorar?</h2><div>${Object.keys(detail).map(x=>`<span>${x}</span>`).join("")}</div></div><button id="financeStart" class="primary large">Comenzar mi autodiagnóstico →</button></section><section id="finance-quiz" class="view quiz"><div class="quiz-top"><button id="financeExit" class="back">← Salir</button><div><span id="financeCounter"></span><i><b id="financeBar"></b></i></div></div><article class="question"><p id="financeDimension" class="kicker teal"></p><h1 id="financeQuestion"></h1><p>¿Con qué frecuencia describe esta afirmación tu manera habitual de actuar?</p><div id="financeOptions" class="options"></div><footer><button id="financePrev" class="secondary">Anterior</button><button id="financeNext" class="primary" disabled>Siguiente</button></footer></article></section><section id="finance-results" class="view"><div id="financeResult"></div></section>`);
document.querySelector(".finance-back").onclick=()=>show("skills");$("financeStart").onclick=start;$("financeExit").onclick=()=>{if(confirm("¿Deseas salir? Este intento no se guardará."))show("finance-skill")};$("financePrev").onclick=()=>{if(current){current--;renderQuestion()}};$("financeNext").onclick=()=>{if(answers[current]===null)return;if(current<23){current++;renderQuestion()}else finish()};progress()}
function start(){let draft;try{draft=JSON.parse(localStorage.getItem(KEY+"-draft")||"null")}catch{}answers=Array.isArray(draft)&&draft.length===24?draft:Array(24).fill(null);let pending=answers.findIndex(x=>x===null);current=pending<0?23:pending;show("finance-quiz");renderQuestion()}
function renderQuestion(){let [d,q]=questions[current];$("financeCounter").textContent=`Pregunta ${current+1} de 24`;$("financeBar").style.width=`${(current+1)/24*100}%`;$("financeDimension").textContent=d;$("financeQuestion").textContent=q;$("financeOptions").innerHTML=labels.map((x,i)=>`<button class="option ${answers[current]===i+1?"selected":""}" data-n="${i+1}"><span>${i+1}</span><small>${x}</small></button>`).join("");$("financeOptions").querySelectorAll("button").forEach(b=>b.onclick=()=>{answers[current]=+b.dataset.n;localStorage.setItem(KEY+"-draft",JSON.stringify(answers));renderQuestion()});$("financePrev").disabled=current===0;$("financeNext").disabled=answers[current]===null;$("financeNext").textContent=current===23?"Ver mis resultados":"Siguiente"}
async function finish(){let dims={};questions.forEach(([d],i)=>(dims[d]??=[]).push(answers[i]));let scores=Object.fromEntries(Object.entries(dims).map(([d,a])=>[d,Math.round(a.reduce((x,y)=>x+y,0)/15*100)])),overall=Math.round(Object.values(scores).reduce((x,y)=>x+y,0)/8),r={date:new Date().toISOString(),overall,scores};localStorage.setItem(KEY,JSON.stringify(r));localStorage.removeItem(KEY+"-draft");renderResult(r);show("finance-results");await sync(r);progress()}
function renderResult(r,message=""){let sorted=Object.entries(r.scores).sort((a,b)=>b[1]-a[1]),strong=sorted[0][0],priority=sorted.at(-1)[0];$("financeResult").innerHTML=`<div class="result-page"><div class="result-hero"><p class="kicker">Competencia 07 · Resultado orientativo</p><h1>Tu perfil financiero-preventivo</h1><div class="score">${r.overall}%</div><h2>Nivel ${level(r.overall)}</h2><p>Fortaleza principal: <b>${strong}</b>. Prioridad de desarrollo: <b>${priority}</b>.</p>${message?`<p class="xp-award">${message}</p>`:""}</div><div class="result-grid">${Object.entries(r.scores).map(([d,n])=>`<article class="dim-result"><header><b>${d}</b><strong>${n}%</strong></header><div><i style="width:${n}%"></i></div><p>${detail[d]}</p></article>`).join("")}</div><aside class="principle"><b>Principio clave</b><p>El análisis económico ayuda a comparar alternativas y asignar recursos; no convierte en aceptable un riesgo que debe controlarse por obligación, ética o criterio preventivo.</p></aside><div class="result-actions"><button id="financeRepeat" class="primary">Repetir</button><button id="financeProgress" class="secondary">Ver mi progreso</button></div></div>`;$("financeRepeat").onclick=start;$("financeProgress").onclick=()=>show("progress")}
async function sync(r){const token=sessionStorage.getItem(TOKEN);if(!token){renderResult(r,"Resultado guardado · Ingresa nuevamente para sincronizar tu progreso");return}try{const res=await fetch(`${URL}/rest/v1/rpc/desarrolla_completar_diagnostico`,{method:"POST",headers:{apikey:API,Authorization:`Bearer ${API}`,"Content-Type":"application/json"},body:JSON.stringify({p_token:token,p_diagnostico:"finanzas_sst",p_puntaje:r.overall,p_nivel:level(r.overall),p_dimensiones:r.scores})}),d=await res.json();renderResult(r,d?.message||"Resultado guardado")}catch(e){console.error(e);renderResult(r,"Resultado guardado · No se pudo sincronizar ahora")}}
function progress(){let r;try{r=JSON.parse(localStorage.getItem(KEY)||"null")}catch{}if(!r)return;$("empty").hidden=true;$("saved").hidden=false;if(!$("financeProgressCard"))$("saved").insertAdjacentHTML("beforeend",`<article id="financeProgressCard" class="featured progress-card"><div class="score">${r.overall}%</div><div><span class="tag ready">Completado</span><h3>Finanzas y Valor Preventivo en SST</h3><p>Nivel ${level(r.overall)} · ${new Date(r.date).toLocaleDateString("es",{dateStyle:"long"})}</p></div><button class="secondary">Ver resultados</button></article>`);const card=$("financeProgressCard");if(card)card.querySelector("button").onclick=()=>{renderResult(r);show("finance-results")}}
build()})();