(()=>{"use strict";
const $=id=>document.getElementById(id),KEY="desarrolla-math-sst-v1";
const concepts=[
 {id:"equation",symbol:"=",title:"Ecuación",question:"¿Cómo se relacionan las variables?",summary:"Una ecuación expresa una relación entre variables. En SST permite convertir datos de campo en magnitudes interpretables.",formula:"C = m / V",formulaText:"Concentración = masa recogida / volumen de aire muestreado",application:"Muestreo de aerosoles: si se recogen 1,5 mg en 0,75 m³, la concentración es 2 mg/m³.",watch:"No basta con sustituir números: revisa unidades, método de medición, supuestos y condiciones de validez."},
 {id:"limit",symbol:"→",title:"Límite",question:"¿Hacia dónde se aproxima una función?",summary:"El límite matemático estudia el comportamiento de una función cuando una variable se acerca a un valor. Ayuda a entender tendencias y es la base conceptual de derivadas e integrales.",formula:"x → a",formulaText:"Observamos qué ocurre cuando x se aproxima a un valor a",application:"Una serie 2, 5, 7, 8,5, 9,2, 9,7, 9,9 sugiere un comportamiento que se aproxima a 10.",watch:"Un límite matemático NO es un límite de exposición ocupacional. TLV, PEL, OEL o VLA son valores técnicos o regulatorios, no conceptos de cálculo."},
 {id:"derivative",symbol:"Δ",title:"Derivada",question:"¿Qué tan rápido está cambiando?",summary:"La derivada describe la tasa de cambio instantánea. Antes de llegar a ella, una tasa promedio ya permite interpretar cómo evoluciona una variable.",formula:"ΔC / Δt",formulaText:"Cambio de concentración / cambio de tiempo",application:"Si una concentración pasa de 2 a 8 ppm en 3 minutos, el cambio promedio es 2 ppm/min.",watch:"Dos áreas pueden mostrar 10 ppm ahora y tener dinámicas muy distintas si una está estable y la otra aumenta rápidamente."},
 {id:"integral",symbol:"∫",title:"Integral",question:"¿Cuánto se acumuló durante un intervalo?",summary:"La integral suma pequeñas contribuciones a lo largo del tiempo. En higiene ocupacional ayuda a comprender la lógica de exposiciones variables y promedios ponderados.",formula:"E = ∫ C(t) dt",formulaText:"Acumulación = suma continua de concentración × pequeños intervalos de tiempo",application:"Si la concentración cambia durante la jornada, cada intervalo aporta una parte a la exposición acumulada.",watch:"La forma exacta de integrar depende del fenómeno. En ruido, por ejemplo, no se promedian dB de forma aritmética: deben respetarse las relaciones energéticas y logarítmicas."}
];
const challenge=[
 {q:"Quieres obtener la concentración a partir de masa recogida y volumen de aire.",a:"equation",why:"Necesitas relacionar variables mediante una expresión matemática."},
 {q:"Un detector marca 8 ppm y quieres saber cuántas ppm aumenta por minuto.",a:"derivative",why:"La pregunta es por una tasa de cambio."},
 {q:"La concentración cambia durante 8 horas y quieres representar toda la exposición del período.",a:"integral",why:"Necesitas acumular contribuciones a lo largo del tiempo."},
 {q:"Una función se acerca cada vez más a un determinado valor y quieres estudiar ese comportamiento.",a:"limit",why:"Esa es la pregunta central del límite matemático."},
 {q:"Dos procesos tienen ahora 10 ppm, pero uno aumenta 3 ppm/min. ¿Qué idea ayuda a diferenciarlos?",a:"derivative",why:"El valor actual es igual; la velocidad de cambio no."},
 {q:"El ruido cambia durante toda la jornada y quieres comprender matemáticamente la idea de exposición acumulada.",a:"integral",why:"La idea general es acumulación en el tiempo, aunque en acústica el cálculo concreto debe respetar energía y escala logarítmica."}
];
const quiz=[
 {q:"¿Qué pregunta responde mejor una ecuación?",opts:["¿Cuánto se acumuló?","¿Cómo se relacionan las variables?","¿Qué tan rápido cambia?","¿Hacia dónde se aproxima?"],a:1},
 {q:"¿Qué describe principalmente una derivada?",opts:["Una tasa de cambio","Un valor legal","Una unidad de medida","Una suma de valores máximos"],a:0},
 {q:"¿Qué idea matemática permite representar acumulación a lo largo del tiempo?",opts:["Límite","Ecuación lineal únicamente","Integral","Porcentaje"],a:2},
 {q:"¿Un límite matemático es lo mismo que un límite de exposición ocupacional?",opts:["Sí, siempre","No, son conceptos distintos","Solo en ruido","Solo si tienen la misma unidad"],a:1},
 {q:"Una concentración pasa de 2 a 8 ppm en 3 minutos. ¿Cuál es la tasa promedio de cambio?",opts:["0,5 ppm/min","2 ppm/min","3 ppm/min","6 ppm/min"],a:1},
 {q:"¿Por qué no conviene usar una fórmula como una simple calculadora?",opts:["Porque las fórmulas no sirven en SST","Porque primero deben entenderse variables, unidades, supuestos y método","Porque todo debe resolverse a mano","Porque solo las usa ingeniería"],a:1}
];
let lessonIndex=0,challengeAnswers=Array(challenge.length).fill(null),quizAnswers=Array(quiz.length).fill(null),quizIndex=0;
function state(){try{return Object.assign({lessons:[false,false,false,false],challenge:false,score:null,completed:false,date:null},JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return{lessons:[false,false,false,false],challenge:false,score:null,completed:false,date:null}}}
function save(patch){const next=Object.assign(state(),patch);localStorage.setItem(KEY,JSON.stringify(next));return next}
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(id)?.classList.add("active");document.querySelectorAll("nav button").forEach(b=>b.classList.remove("active"));scrollTo({top:0,behavior:"smooth"})}
function toast(msg){const t=$("toast");if(!t)return;t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
function pathMenu(){const s=state(),learned=s.lessons.filter(Boolean).length===4;return`<div class="path-menu math-path-menu"><button class="path-step ${learned?"done":""}" data-math-nav="learn"><b>${learned?"✓":"1"}</b><div><span>Aprende</span><small>4 conceptos esenciales</small></div></button><button class="path-step ${s.challenge?"done":""}" data-math-nav="challenge"><b>${s.challenge?"✓":"2"}</b><div><span>Aplica</span><small>6 situaciones de SST</small></div></button><button class="path-step ${s.completed?"done":""}" data-math-nav="quiz"><b>${s.completed?"✓":"3"}</b><div><span>Demuestra</span><small>Evaluación final</small></div></button></div>`}
function bindNav(){document.querySelectorAll("[data-math-nav]").forEach(b=>b.onclick=()=>{const x=b.dataset.mathNav;if(x==="home"){renderHome();show("math-sst-home")}if(x==="skills")show("skills");if(x==="learn"){lessonIndex=0;renderLesson();show("math-sst-learn")}if(x==="challenge"){renderChallenge();show("math-sst-challenge")}if(x==="quiz"){startQuiz();show("math-sst-quiz")}})}
function renderHome(){const s=state();$("mathHomeRoot").innerHTML=`<div class="route-shell"><button class="back" data-math-nav="skills">← Volver a competencias</button><div class="module math-module"><div><span class="tag ready">Micro-ruta técnica</span><h1>Matemáticas aplicadas para el profesional de SST</h1><p>Comprende cuatro ideas de cálculo que aparecen detrás de mediciones, exposición y análisis técnico: ecuación, límite, derivada e integral.</p></div><div class="facts"><span><b>4</b>conceptos</span><span><b>6</b>casos</span><span><b>20–30</b>minutos</span></div></div><aside class="notice"><b>No es un curso de cálculo.</b> El objetivo es reconocer qué pregunta responde cada herramienta matemática y cómo interpretar su uso en SST.</aside>${pathMenu()}<div class="math-concept-grid">${concepts.map(c=>`<article class="route-card math-concept"><i>${c.symbol}</i><h2>${c.title}</h2><strong>${c.question}</strong><p>${c.summary}</p></article>`).join("")}</div><article class="route-card"><h2>El mapa mental</h2><div class="math-memory"><span><b>Ecuación</b>Relacionar</span><span><b>Límite</b>Aproximarse</span><span><b>Derivada</b>Cambiar</span><span><b>Integral</b>Acumular</span></div><div class="route-buttons"><button class="primary" data-math-nav="learn">${s.lessons.some(Boolean)?"Continuar aprendiendo →":"Comenzar la micro-ruta →"}</button></div></article></div>`;bindNav()}
function lessonTool(c){if(c.id==="equation")return`<div class="math-calc"><h3>Prueba la ecuación</h3><div class="math-fields"><label>Masa recogida (mg)<input id="mathMass" type="number" step="0.01" value="1.5"></label><label>Volumen (m³)<input id="mathVolume" type="number" step="0.01" value="0.75"></label></div><button id="mathEqCalc" class="secondary">Calcular concentración</button><p id="mathEqResult" class="math-output">Resultado esperado: 2 mg/m³</p></div>`;
if(c.id==="limit")return`<div class="math-calc"><h3>Observa la tendencia</h3><p class="math-sequence">2 → 5 → 7 → 8,5 → 9,2 → 9,7 → 9,9 → ?</p><div class="math-choice-grid"><button data-limit="8">8</button><button data-limit="10">10</button><button data-limit="20">20</button></div><p id="mathLimitResult" class="math-output">Selecciona el valor al que parece aproximarse la secuencia.</p></div>`;
if(c.id==="derivative")return`<div class="math-calc"><h3>Calcula una tasa de cambio promedio</h3><div class="math-fields three"><label>Inicial (ppm)<input id="mathC1" type="number" value="2"></label><label>Final (ppm)<input id="mathC2" type="number" value="8"></label><label>Tiempo (min)<input id="mathDt" type="number" value="3"></label></div><button id="mathDerCalc" class="secondary">Calcular ppm/min</button><p id="mathDerResult" class="math-output">Resultado esperado: 2 ppm/min</p></div>`;
return`<div class="math-calc"><h3>Acumula una exposición simplificada</h3><p>Ejemplo por intervalos: 1 h×2 ppm + 2 h×5 ppm + 1 h×8 ppm + 4 h×1 ppm.</p><button id="mathIntCalc" class="secondary">Calcular acumulación y promedio</button><p id="mathIntResult" class="math-output">Pulsa calcular para ver cómo cada intervalo aporta al total.</p><small>Ejemplo didáctico. La interpretación higiénica real depende del contaminante, método y criterio aplicable.</small></div>`}
function renderLesson(){const c=concepts[lessonIndex],s=state();$("mathLearnRoot").innerHTML=`<div class="route-shell"><button class="back" data-math-nav="home">← Volver a la micro-ruta</button><div class="route-head"><span class="route-badge">Paso 1 · Aprende</span><h1>${c.symbol} ${c.title}</h1><p>${c.question}</p></div><div class="lesson-nav">${concepts.map((x,i)=>`<button data-math-lesson="${i}" class="${i===lessonIndex?"active":""} ${s.lessons[i]?"done":""}">${i+1}</button>`).join("")}</div><article class="route-card"><div class="lesson-grid"><div><p class="kicker teal">Concepto ${lessonIndex+1} de 4</p><h2>${c.title}: ${c.question}</h2><p>${c.summary}</p><div class="math-formula"><b>${c.formula}</b><span>${c.formulaText}</span></div><div class="example-box"><b>Aplicación SST</b><p>${c.application}</p></div></div><div>${lessonTool(c)}<div class="alert-box"><b>Cuidado técnico</b><p>${c.watch}</p></div></div></div><div class="route-buttons"><button id="mathPrevLesson" class="secondary" ${lessonIndex===0?"disabled":""}>← Anterior</button><button id="mathNextLesson" class="primary">${lessonIndex===3?"Completar y aplicar →":"Entendido, siguiente →"}</button></div></article></div>`;bindNav();document.querySelectorAll("[data-math-lesson]").forEach(b=>b.onclick=()=>{lessonIndex=+b.dataset.mathLesson;renderLesson()});$("mathPrevLesson").onclick=()=>{lessonIndex--;renderLesson()};$("mathNextLesson").onclick=()=>{const st=state(),done=[...st.lessons];done[lessonIndex]=true;save({lessons:done});if(lessonIndex<3){lessonIndex++;renderLesson()}else{renderChallenge();show("math-sst-challenge")}};bindLessonTool(c)}
function bindLessonTool(c){if(c.id==="equation")$("mathEqCalc").onclick=()=>{const m=+$("mathMass").value,v=+$("mathVolume").value;$("mathEqResult").textContent=v>0&&Number.isFinite(m/v)?`C = ${m} / ${v} = ${(m/v).toFixed(2)} mg/m³`:"Revisa los valores; el volumen debe ser mayor que cero."};
if(c.id==="limit")document.querySelectorAll("[data-limit]").forEach(b=>b.onclick=()=>{$("mathLimitResult").textContent=b.dataset.limit==="10"?"Correcto: la secuencia parece aproximarse a 10. Eso ilustra la idea de límite.":"Observa los últimos valores: cada vez están más cerca de 10."});
if(c.id==="derivative")$("mathDerCalc").onclick=()=>{const a=+$("mathC1").value,b=+$("mathC2").value,t=+$("mathDt").value;$("mathDerResult").textContent=t>0?`ΔC/Δt = (${b} − ${a}) / ${t} = ${((b-a)/t).toFixed(2)} ppm/min`:"El intervalo de tiempo debe ser mayor que cero."};
if(c.id==="integral")$("mathIntCalc").onclick=()=>{$("mathIntResult").textContent="Acumulación simplificada = 24 ppm·h. Tiempo total = 8 h. Promedio ponderado = 3 ppm."}}
function renderChallenge(){challengeAnswers=Array(challenge.length).fill(null);$("mathChallengeRoot").innerHTML=`<div class="route-shell"><button class="back" data-math-nav="home">← Volver a la micro-ruta</button><div class="route-head"><span class="route-badge">Paso 2 · Aplica</span><h1>¿Qué herramienta matemática necesitas?</h1><p>No calcules todavía. Primero reconoce qué pregunta técnica estás intentando responder.</p></div><div class="math-challenge-list">${challenge.map((x,i)=>`<article class="route-card math-challenge" id="mathCase${i}"><p class="kicker teal">Caso ${i+1}</p><h2>${x.q}</h2><div class="math-choice-grid four">${concepts.map(c=>`<button data-case="${i}" data-answer="${c.id}">${c.symbol} ${c.title}</button>`).join("")}</div><p class="math-feedback" id="mathCaseFeedback${i}"></p></article>`).join("")}</div><div class="route-buttons"><button id="mathFinishChallenge" class="primary" disabled>Completar aplicación →</button></div></div>`;bindNav();document.querySelectorAll("[data-case]").forEach(b=>b.onclick=()=>{const i=+b.dataset.case,ok=b.dataset.answer===challenge[i].a;challengeAnswers[i]=b.dataset.answer;const card=$(`mathCase${i}`);card.querySelectorAll("button").forEach(x=>x.classList.remove("selected","correct","incorrect"));b.classList.add("selected",ok?"correct":"incorrect");$(`mathCaseFeedback${i}`).innerHTML=`<b>${ok?"Correcto":"Revisa la pregunta"}.</b> ${challenge[i].why}`;$("mathFinishChallenge").disabled=challengeAnswers.some(x=>x===null)});$("mathFinishChallenge").onclick=()=>{save({challenge:true});startQuiz();show("math-sst-quiz")}}
function startQuiz(){quizAnswers=Array(quiz.length).fill(null);quizIndex=0;renderQuiz()}
function renderQuiz(){const x=quiz[quizIndex];$("mathQuizRoot").innerHTML=`<div class="route-shell"><div class="quiz-top"><button class="back" data-math-nav="home">← Salir</button><div><span>Pregunta ${quizIndex+1} de ${quiz.length}</span><i><b style="width:${(quizIndex+1)/quiz.length*100}%"></b></i></div></div><article class="question"><p class="kicker teal">Paso 3 · Demuestra</p><h1>${x.q}</h1><div class="options">${x.opts.map((o,i)=>`<button class="option ${quizAnswers[quizIndex]===i?"selected":""}" data-qopt="${i}"><span>${String.fromCharCode(65+i)}</span><small>${o}</small></button>`).join("")}</div><footer><button id="mathQuizPrev" class="secondary" ${quizIndex===0?"disabled":""}>Anterior</button><button id="mathQuizNext" class="primary" ${quizAnswers[quizIndex]===null?"disabled":""}>${quizIndex===quiz.length-1?"Ver resultado":"Siguiente"}</button></footer></article></div>`;bindNav();document.querySelectorAll("[data-qopt]").forEach(b=>b.onclick=()=>{quizAnswers[quizIndex]=+b.dataset.qopt;renderQuiz()});$("mathQuizPrev").onclick=()=>{quizIndex--;renderQuiz()};$("mathQuizNext").onclick=()=>{if(quizAnswers[quizIndex]===null)return;if(quizIndex<quiz.length-1){quizIndex++;renderQuiz()}else finishQuiz()}}
function finishQuiz(){const hits=quiz.reduce((n,q,i)=>n+(quizAnswers[i]===q.a?1:0),0),score=Math.round(hits/quiz.length*100),completed=score>=80,prev=state();save({score,completed:completed||prev.completed,date:new Date().toISOString()});renderResult(score,hits,completed);show("math-sst-result")}
function renderResult(score,hits,passed){$("mathResultRoot").innerHTML=`<div class="route-shell"><button class="back" data-math-nav="home">← Volver a la micro-ruta</button><article class="route-card math-result"><span class="route-badge">Evaluación completada</span><h1>${passed?"Comprendes la lógica matemática esencial":"Conviene repasar antes de cerrar la ruta"}</h1><div class="math-score">${score}%</div><p>Respuestas correctas: <b>${hits} de ${quiz.length}</b>. Para completar esta micro-ruta necesitas al menos 80 %.</p>${passed?`<div class="principle"><b>Micro-ruta completada</b><p>Ya puedes reconocer cuándo un problema de SST exige relacionar variables, estudiar una aproximación, analizar una tasa de cambio o comprender una acumulación.</p></div>`:`<div class="alert-box"><b>Qué hacer ahora</b><p>Repasa especialmente las cuatro preguntas: relacionar, aproximarse, cambiar y acumular. Luego intenta nuevamente.</p></div>`}<div class="route-buttons"><button class="secondary" data-math-nav="learn">Repasar conceptos</button><button id="mathRepeatQuiz" class="primary">${passed?"Repetir evaluación":"Intentar nuevamente"}</button></div></article><article class="route-card"><h2>Idea final</h2><blockquote>El profesional de SST no necesita convertirse en matemático. Necesita comprender suficientemente las matemáticas para no utilizar una fórmula sin entender el fenómeno que representa.</blockquote><p><b>La Movida de SST+ · De la Reacción a la Prevención · www.movidasst.com</b></p></article></div>`;bindNav();$("mathRepeatQuiz").onclick=()=>{startQuiz();show("math-sst-quiz")};if(passed)toast("Micro-ruta de Matemáticas aplicadas completada")}
function mount(){const grid=document.querySelector("#skills .grid");if(grid&&!document.getElementById("mathSstCard"))grid.insertAdjacentHTML("beforeend",`<article id="mathSstCard" class="card available math-card"><div class="icon cyan">∫</div><span class="tag ready">Micro-ruta técnica</span><h2>Matemáticas aplicadas para el profesional de SST</h2><p>Entiende ecuaciones, límites, derivadas e integrales mediante situaciones de ruido, gases, muestreo y exposición.</p><button id="mathOpen" class="primary full">Abrir micro-ruta</button></article>`);document.querySelector("main").insertAdjacentHTML("beforeend",`<section id="math-sst-home" class="view"><div id="mathHomeRoot"></div></section><section id="math-sst-learn" class="view"><div id="mathLearnRoot"></div></section><section id="math-sst-challenge" class="view"><div id="mathChallengeRoot"></div></section><section id="math-sst-quiz" class="view"><div id="mathQuizRoot"></div></section><section id="math-sst-result" class="view"><div id="mathResultRoot"></div></section>`);$("mathOpen").onclick=()=>{renderHome();show("math-sst-home")};renderHome()}
mount();
})();