(()=>{"use strict";const U="https://lfdmbkzghnwvsapxypvt.supabase.co",K="sb_publishable_bRnkA6PA8-v073nrw9zxiQ_8rVGiOn1",T="desarrolla-ranking-token",seen=new Set(),map={
"desarrolla-neg-learn-v1":["negociacion","guia"],"desarrolla-neg-role-v1":["negociacion","practica"],"desarrolla-neg-plan-v1":["negociacion","plan"],
"desarrolla-comm-learn-v1":["comunicacion_asertiva","guia"],"desarrolla-comm-role-v1":["comunicacion_asertiva","practica"],"desarrolla-comm-plan-v1":["comunicacion_asertiva","plan"],
"desarrolla-lead-learn-v1":["liderazgo_preventivo","guia"],"desarrolla-lead-role-v1":["liderazgo_preventivo","practica"],"desarrolla-lead-plan-v1":["liderazgo_preventivo","plan"],
"desarrolla-inf-learn-v1":["influencia_estrategica","guia"],"desarrolla-inf-role-v1":["influencia_estrategica","practica"],"desarrolla-inf-plan-v1":["influencia_estrategica","plan"],
"desarrolla-crit-learn-v1":["pensamiento_critico","guia"],"desarrolla-crit-prebunk-v1":["pensamiento_critico","prebunking"],"desarrolla-crit-role-v1":["pensamiento_critico","practica"],"desarrolla-crit-plan-v1":["pensamiento_critico","plan"],
"desarrolla-emo-learn-v1":["gestion_emocional","guia"],"desarrolla-emo-role-v1":["gestion_emocional","practica"],"desarrolla-emo-plan-v1":["gestion_emocional","plan"],
"desarrolla-fin-learn-v1":["finanzas_sst","guia"],"desarrolla-fin-role-v1":["finanzas_sst","practica"],"desarrolla-fin-plan-v1":["finanzas_sst","plan"]};
async function send(key,value){const token=sessionStorage.getItem(T),cfg=map[key];if(!token||!cfg||!value)return;const mark=key+":"+value;if(seen.has(mark))return;let metadata={};if(cfg[1]==="practica")try{let x=JSON.parse(value);metadata={score:Number(x.score)||0,contexto:String(x.actor||x.case||x.scenario||"").slice(0,100),version:2}}catch{}else if(cfg[1]==="plan")try{let x=JSON.parse(value);metadata={dimension:String(x.dimension||"").slice(0,120),situacion:String(x.situation||"").slice(0,800),accion:String(x.action||"").slice(0,800),evidencia:String(x.evidence||"").slice(0,300),fecha:String(x.date||"").slice(0,20),version:2}}catch{}else if(cfg[1]==="prebunking")try{let x=JSON.parse(value);metadata={score:Number(x.score)||0,completado:true,casos:Array.isArray(x.answers)?x.answers.length:0,correctos:Array.isArray(x.answers)?x.answers.filter(a=>a?.ok).length:0,perfil:Array.isArray(x.profile)?x.profile.map(p=>({key:String(p.key||""),score:Number(p.score)||0,correct:Number(p.correct)||0,total:Number(p.total)||0})):[],version:2}}catch{metadata={score:0,completado:true,version:2}}else if(cfg[1]==="guia")metadata={version:2,estaciones:(cfg[0]==="finanzas_sst"||cfg[0]==="pensamiento_critico")?7:6};seen.add(mark);try{let r=await fetch(`${U}/rest/v1/rpc/desarrolla_registrar_etapa`,{method:"POST",headers:{apikey:K,Authorization:`Bearer ${K}`,"Content-Type":"application/json"},body:JSON.stringify({p_token:token,p_diagnostico:cfg[0],p_etapa:cfg[1],p_metadata:metadata})}),d=await r.json();if(!d?.ok)seen.delete(mark);else document.dispatchEvent(new CustomEvent("desarrolla:progress-updated",{detail:{competency:cfg[0],stage:cfg[1]}}))}catch(e){seen.delete(mark);console.error("No se pudo sincronizar el avance",e)}}
function scan(){Object.keys(map).forEach(k=>{let v=localStorage.getItem(k);if(v)send(k,v)})}const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){original.call(this,key,value);if(this===localStorage&&map[key])setTimeout(()=>send(key,String(value)),0)};addEventListener("online",scan);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")scan()});window.DesarrollaSyncProgress=scan;scan();let attempts=0,timer=setInterval(()=>{scan();if(++attempts>=20)clearInterval(timer)},3000)})();
