(()=>{"use strict";
const U="https://lfdmbkzghnwvsapxypvt.supabase.co",K="sb_publishable_bRnkA6PA8-v073nrw9zxiQ_8rVGiOn1",TOKEN="desarrolla-ranking-token",SESSION="desarrolla-session",ADMIN="desarrolla-admin-preview-v1";
const results={
 "desarrolla-negociacion-v1":"negociacion","desarrolla-comunicacion-v1":"comunicacion_asertiva","desarrolla-liderazgo-v1":"liderazgo_preventivo","desarrolla-influencia-v1":"influencia_estrategica","desarrolla-pensamiento-v1":"pensamiento_critico","desarrolla-emocional-v1":"gestion_emocional","desarrolla-finanzas-v1":"finanzas_sst"
},sent=new Map();let syncing=false,currentModal=null,returnFocus=null,statusTimer,wasOffline=!navigator.onLine;
const main=document.querySelector("#app main");if(main)main.id="mainContent";
if(!document.querySelector(".skip-link")){const a=document.createElement("a");a.className="skip-link";a.href="#mainContent";a.textContent="Saltar al contenido principal";document.body.prepend(a)}
const status=document.createElement("div");status.id="systemStatus";status.className="system-status";status.setAttribute("role","status");status.setAttribute("aria-live","polite");status.hidden=true;document.body.appendChild(status);
function message(text,type="info",temporary=false){clearTimeout(statusTimer);status.textContent=text;status.dataset.type=type;status.hidden=!text;if(temporary&&text)statusTimer=setTimeout(()=>{status.hidden=true},4200)}
function level(n){return n<45?"Inicial":n<65?"En desarrollo":n<82?"Aplicación consistente":"Fortaleza declarada"}
async function syncResults(){if(syncing||!navigator.onLine)return;const token=sessionStorage.getItem(TOKEN);if(!token)return;syncing=true;let recovered=0;try{for(const [key,code] of Object.entries(results)){const raw=localStorage.getItem(key);if(!raw||sent.get(key)===raw)continue;let value;try{value=JSON.parse(raw)}catch{continue}if(!Number.isFinite(value?.overall)||!value?.scores)continue;try{const response=await fetch(`${U}/rest/v1/rpc/desarrolla_completar_diagnostico`,{method:"POST",headers:{apikey:K,Authorization:`Bearer ${K}`,"Content-Type":"application/json"},body:JSON.stringify({p_token:token,p_diagnostico:code,p_puntaje:value.overall,p_nivel:level(value.overall),p_dimensiones:value.scores})}),data=await response.json();if(data?.ok){sent.set(key,raw);recovered++;document.dispatchEvent(new CustomEvent("desarrolla:progress-updated",{detail:{competency:code,stage:"diagnostico"}}))}else if(/sesión|token/i.test(data?.message||"")){sessionStorage.removeItem(TOKEN);message("Tu sesión de sincronización venció. Sal e ingresa nuevamente para proteger los próximos avances.","warning");break}}catch(error){console.error("Sincronización pendiente",error);break}}if(recovered)message(`Progreso sincronizado: ${recovered} resultado${recovered===1?"":"s"} actualizado${recovered===1?"":"s"}.`,"success",true)}finally{syncing=false}}
function connection(){if(!navigator.onLine){wasOffline=true;message("Sin conexión. Puedes continuar; conservaremos el avance en este dispositivo y lo sincronizaremos al volver internet.","offline")}else{if(wasOffline)message("Conexión recuperada. Estamos sincronizando tu avance…","success",true);wasOffline=false;window.DesarrollaSyncProgress?.();syncResults()}}
function sessionCheck(){const app=document.getElementById("app"),participant=sessionStorage.getItem(SESSION),token=sessionStorage.getItem(TOKEN),admin=sessionStorage.getItem(ADMIN);if(app&&!app.hidden&&participant&&!token&&!admin)message("Tu avance se conserva aquí, pero la sincronización con el ranking no está activa. Sal e ingresa nuevamente antes de terminar una ruta.","warning")}
function focusables(modal){return[...modal.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(x=>!x.hidden&&x.getClientRects().length)}
function modal(){return[...document.querySelectorAll('#expertModal,#paymentModal,#certificateModal,#adminPreviewModal,[role="dialog"]')].find(x=>!x.hidden&&x.getClientRects().length)||null}
function modalFocus(){const next=modal();if(next===currentModal)return;if(next){returnFocus=document.activeElement;currentModal=next;const dialog=next.matches('[role="dialog"]')?next:next.querySelector('[role="dialog"],.expert-dialog,.certificate-dialog,.admin-preview-dialog')||next;dialog.setAttribute("role","dialog");dialog.setAttribute("aria-modal","true");setTimeout(()=>focusables(dialog)[0]?.focus(),20)}else if(currentModal){currentModal=null;if(returnFocus?.isConnected)returnFocus.focus();returnFocus=null}}
addEventListener("keydown",event=>{if(event.key!=="Tab")return;const m=modal();if(!m)return;const list=focusables(m);if(!list.length)return;const first=list[0],last=list.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});
addEventListener("online",connection);addEventListener("offline",connection);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"){connection();sessionCheck()}});
new MutationObserver(()=>modalFocus()).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:["hidden"]});
setTimeout(()=>{if(!navigator.onLine)connection();syncResults();sessionCheck();modalFocus()},1800);setTimeout(sessionCheck,5000);
window.DesarrollaRecovery={sync:syncResults,status:message};
})();
