(()=>{"use strict";
const CONFIG=[
 {root:"roleRoot",key:"desarrolla-neg-role-v1",criteria:["Apertura y diagnóstico","Opciones y criterios","Acuerdo y seguimiento"],benchmark:["Explora intereses y evidencia sin abandonar el límite preventivo.","Compara alternativas seguras con criterios verificables y riesgo residual.","Formaliza responsables, recursos, fechas, verificación y escalamiento."]},
 {root:"crroot",key:"desarrolla-comm-role-v1",criteria:["Escucha y encuadre","Mensaje y petición","Cierre y trazabilidad"],benchmark:["Escucha, reformula y separa hechos de interpretaciones.","Comunica el riesgo con claridad y formula una petición concreta.","Confirma comprensión y registra acciones, responsables y desacuerdos."]},
 {root:"lrroot",key:"desarrolla-lead-role-v1",criteria:["Coherencia y confianza","Decisión participativa","Responsabilidad y seguimiento"],benchmark:["Modela la conducta esperada y crea condiciones para hablar sin temor.","Integra evidencia, participación y límites preventivos al decidir.","Asigna responsabilidades, verifica avances y afronta incumplimientos."]},
 {root:"irroot",key:"desarrolla-inf-role-v1",criteria:["Lectura del contexto","Argumentación estratégica","Movilización y seguimiento"],benchmark:["Identifica decisores, aliados, restricciones y oportunidad de influencia.","Conecta evidencia de SST con continuidad, desempeño y consecuencias.","Obtiene una decisión concreta y mantiene el control en la agenda."]},
 {root:"krroot",key:"desarrolla-crit-role-v1",criteria:["Definición del problema","Calidad del razonamiento","Revisión de la decisión"],benchmark:["Delimita el problema y evita confundirlo con una solución anticipada.","Contrasta fuentes, supuestos, sesgos, causalidad y alternativas.","Define indicadores, incertidumbre y evidencia que podría cambiar la decisión."]},
 {root:"erroot",key:"desarrolla-emo-role-v1",criteria:["Autoconciencia y pausa","Regulación y desescalamiento","Límites y recuperación"],benchmark:["Reconoce el activador y crea una pausa antes de responder.","Valida el impacto sin ceder el criterio preventivo y reduce la tensión.","Establece límites, acuerda el siguiente paso y busca apoyo cuando corresponde."]},
 {root:"frroot",key:"desarrolla-fin-role-v1",criteria:["Lectura económica del riesgo","Comparación de alternativas","Gobernanza del valor"],benchmark:["Traduce el riesgo a consecuencias operativas y financieras sin reducir la SST a dinero.","Compara CAPEX, OPEX, costo total, incertidumbre y riesgo residual con supuestos transparentes.","Cierra con decisión, responsable, recursos, indicador de eficacia y fecha de revisión."]}
];
const style=document.createElement("style");style.textContent=`.role-debrief{margin:24px 0;text-align:left}.role-debrief h2{color:#00205b;margin-bottom:6px}.role-debrief>p{color:#64748b}.decision-review{display:grid;gap:12px;margin:18px 0}.decision-review article{border:1px solid #dce5ed;border-radius:16px;padding:16px;background:#fff}.decision-review header{display:flex;justify-content:space-between;gap:12px;align-items:center}.decision-review h3{font-size:1rem;margin:0;color:#00205b}.decision-review .decision-score{border-radius:999px;padding:4px 9px;font-size:.76rem;font-weight:800}.decision-score.solid{background:#eaf6e4;color:#3f7424}.decision-score.partial{background:#fff5d6;color:#845e00}.decision-score.risk{background:#ffe9e5;color:#a12f24}.decision-review blockquote{margin:12px 0;padding:10px 12px;border-left:3px solid #007b85;background:#f8fafc;color:#334155}.decision-review p{margin:8px 0;color:#64748b}.senior-model{background:linear-gradient(135deg,#00205b,#007b85);color:#fff;border-radius:18px;padding:18px;margin:16px 0}.senior-model h3{margin:0 0 10px}.senior-model ol{margin:0;padding-left:20px}.senior-model li+li{margin-top:8px}.reflection-box{border:1px solid #b9dadd;background:#f2fbfb;border-radius:16px;padding:16px}.adaptive-outcome{border:1px solid #cfe7e8;background:#f8ffff;border-radius:16px;padding:16px;margin:16px 0}.adaptive-outcome>span{font-size:.75rem;font-weight:800;text-transform:uppercase;letter-spacing:.05em;color:#007b85}.adaptive-outcome h3{margin:5px 0;color:#00205b}.adaptive-outcome p{margin:6px 0;color:#475569}.adaptive-outcome small{color:#64748b;font-weight:700}.reflection-box ul{margin-bottom:0}@media(max-width:620px){.decision-review header{align-items:flex-start;flex-direction:column}.decision-review article,.senior-model,.reflection-box{padding:14px}}`;document.head.appendChild(style);
function read(k){try{return JSON.parse(localStorage.getItem(k)||"null")}catch{return null}}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function label(n){return n>=2?["Respuesta sólida","solid"]:n>=0?["Respuesta parcial","partial"]:["Respuesta de riesgo","risk"]}
function mount(c){const root=document.getElementById(c.root);if(!root||root.querySelector(".role-debrief"))return;const marker=[...root.querySelectorAll(".route-badge")].some(x=>/completad|caso completado/i.test(x.textContent));if(!marker)return;const data=read(c.key),trace=data?.history||data?.trace;if(!Array.isArray(trace)||!trace.length)return;const buttons=root.querySelector(".route-buttons");if(!buttons)return;const box=document.createElement("section");box.className="role-debrief";box.innerHTML=`<h2>Debrief de tu actuación</h2><p>Revisa el criterio utilizado, no solamente la puntuación. Una respuesta técnicamente correcta también debe ser comprensible, aplicable y verificable.</p><div class="decision-review">${trace.map((x,i)=>{const [txt,cls]=label(Number(x.points)),benchmark=c.benchmark[i]||"Integra la rúbrica de la competencia, el efecto sobre las personas y la trazabilidad de la decisión.",heading=c.criteria[i]||`Decisión ${i+1}`;return`<article><header><h3>${i+1}. ${esc(heading)}</h3><span class="decision-score ${cls}">${txt}</span></header><blockquote>${esc(x.choice)}</blockquote><p><b>Consecuencia:</b> ${esc(x.feedback||"Revisa el efecto de esta decisión sobre las personas, el control y la confianza.")}</p><p><b>Criterio senior:</b> ${esc(benchmark)}</p></article>`}).join("")}</div><div class="senior-model"><h3>Secuencia de referencia</h3><ol>${c.benchmark.map(x=>`<li>${esc(x)}</li>`).join("")}</ol></div><div class="reflection-box"><b>Antes de crear tu plan, responde mentalmente:</b><ul><li>¿Qué información te faltó pedir o verificar?</li><li>¿Qué efecto produjo tu elección en la confianza y en el control del riesgo?</li><li>¿Qué frase o conducta cambiarás en una situación real?</li></ul></div>`;buttons.parentNode.insertBefore(box,buttons)}
function scan(){CONFIG.forEach(mount)}
new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});scan();
})();
